import type { ReactNode } from 'react'

export const TEAL = '#2293B4'

export const OUTCOME_CARDS: { id: string; title: string; description: string; icon: ReactNode }[] = [
  { id: 'skill-development', title: 'Skill Development', description: 'Build technical or behavioral capabilities', icon: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10" /><circle cx="12" cy="12" r="6" /><circle cx="12" cy="12" r="2" /></svg> },
  { id: 'revenue-generation', title: 'Revenue Generation', description: 'Generate leads, sales, or partnerships', icon: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18" /><polyline points="17 6 23 6 23 12" /></svg> },
  { id: 'hiring-talent', title: 'Hiring & Talent', description: 'Attract, assess, and hire talent', icon: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" /><circle cx="9" cy="7" r="4" /><line x1="19" y1="8" x2="19" y2="14" /><line x1="22" y1="11" x2="16" y2="11" /></svg> },
  { id: 'brand-positioning', title: 'Brand Positioning', description: 'Build thought leadership & visibility', icon: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" /></svg> },
  { id: 'leadership-alignment', title: 'Leadership Alignment', description: 'Align strategy, vision, and execution', icon: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" /><circle cx="9" cy="7" r="4" /><path d="M23 21v-2a4 4 0 0 0-3-3.87" /><path d="M16 3.13a4 4 0 0 1 0 7.75" /></svg> },
  { id: 'innovation-problem-solving', title: 'Innovation & Problem Solving', description: 'Solve complex business challenges', icon: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 18h6" /><path d="M10 22h4" /><path d="M15.09 14c.18-.98.65-1.74 1.41-2.5A4.65 4.65 0 0 0 18 8 6 6 0 0 0 6 8c0 1 .23 2.23 1.5 3.5A4.61 4.61 0 0 1 8.91 14" /></svg> },
  { id: 'compliance-risk', title: 'Compliance & Risk', description: 'Meet regulatory & governance needs', icon: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" /></svg> },
  { id: 'community-networking', title: 'Community & Networking', description: 'Build meaningful connections', icon: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></svg> },
  { id: 'product-adoption', title: 'Product Adoption', description: 'Drive product usage & engagement', icon: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" /></svg> },
  { id: 'behavior-change', title: 'Behavior Change', description: 'Transform mindsets and behaviors', icon: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="20" x2="18" y2="10" /><line x1="12" y1="20" x2="12" y2="4" /><line x1="6" y1="20" x2="6" y2="14" /></svg> },
]

export const SKILL_TYPE_OPTIONS = ['Technical', 'Functional', 'Behavioural', 'Leadership']
export const REVENUE_TYPE_OPTIONS = ['Lead generation', 'Sales conversion', 'Partnerships']
export const TARGET_AUDIENCE_OPTIONS = ['Client', 'Partners', 'Investors']
export const HIRING_GOAL_OPTIONS = ['Bulk hiring', 'Specialised roles', 'Pipeline building']
export const ASSESSMENT_TYPE_OPTIONS = ['Screening', 'Interview', 'Hackathon']
export const POSITIONING_GOAL_OPTIONS = ['Thought Leadership', 'Awareness', 'Reputation']
export const ALIGNMENT_TYPE_OPTIONS = ['Strategy', 'Vision', 'Execution']
export const LEADERSHIP_LEVEL_OPTIONS = ['Mid level', 'Senior', 'Executive']
export const PROBLEM_TYPE_OPTIONS = ['Business', 'Technical', 'Product', 'Process']
export const COMPLIANCE_TYPE_OPTIONS = ['Legal', 'ESG', 'Data privacy', 'AI ethics', 'POSH']
export const NETWORKING_TYPE_OPTIONS = ['Peer networking', 'Expert networking', 'Investor networking', 'Alumini networking']
export const RELATIONSHIP_DEPTH_OPTIONS = ['Surface Level', 'Deep Relationship']
export const ADOPTION_STAGE_OPTIONS = ['Awareness', 'Trial', 'Active Use']
export const BEHAVIOUR_TYPE_OPTIONS = ['Productivity', 'Leadership', 'Sales', 'Mindset']
export const AUDIENCE_OPTIONS = ['Students', 'Job Seekers', 'Entry Level Employees', 'Individual Contributors', 'Managers', 'Senior Managers', 'Leaders', 'Executives', 'Founders', 'Entrepreneurs', 'Sales Team', 'Marketing Team', 'HR Team', 'Tech Team', 'Product Team', 'Operations Team', 'Finance Team', 'Cross-Functional Team', 'Customers', 'Partners', 'Investors', 'Community Members']
export const SENIORITY_OPTIONS = ['Student', 'Intern', 'Junior', 'Mid-Level', 'Senior', 'Lead', 'Director', 'VP', 'C-Suite', 'Founder']
export const PRIOR_KNOWLEDGE_OPTIONS = [{ id: 'L1', label: 'L1: No Exposure' }, { id: 'L2', label: 'L2: Basic Awareness' }, { id: 'L3', label: 'L3: Working Knowledge' }, { id: 'L4', label: 'L4: Advanced Practitioner' }, { id: 'L5', label: 'L5: Expert Level' }]
export const FUNCTIONAL_BACKGROUND_OPTIONS = ['Engineering', 'Product Management', 'Design', 'Marketing', 'Sales', 'Customer Success', 'Operations', 'Finance', 'Human Resources', 'Legal', 'Data Science', 'Analytics', 'Consulting', 'General Management', 'Entrepreneurship', 'Mixed']
export const INDUSTRY_CONTEXT_OPTIONS = ['Technology', 'SaaS', 'FinTech', 'Healthcare', 'Education', 'E-Commerce', 'Manufacturing', 'Logistics', 'Consulting', 'Media', 'Telecom', 'Government', 'Non-Profit', 'Real Estate', 'Energy', 'Agriculture', 'Cross-Industry']
export const RESISTANCE_OPTIONS = [{ id: 'low', label: 'Low', sub: 'Engaged & willing' }, { id: 'medium', label: 'Medium', sub: 'Neutral, needs convincing' }, { id: 'high', label: 'High', sub: 'Skeptical or resistant' }]
export const LEARNING_VS_ACTION_BIAS_OPTIONS = ['Learning-Oriented', 'Action-Oriented', 'Mixed']
export const ENGAGEMENT_DEPTH_OPTIONS = [{ id: '1', title: 'Awareness', description: 'High-level overview, inspiration' }, { id: '2', title: 'Introduction', description: 'Basic concepts and frameworks' }, { id: '3', title: 'Working Knowledge', description: 'Practical application and tools' }, { id: '4', title: 'Proficiency', description: 'Deep dive with hands-on practice' }, { id: '5', title: 'Mastery', description: 'Advanced techniques and coaching' }]
export const EXPECTED_DELIVERABLES = [{ id: 'knowledge-materials', label: 'Knowledge Materials', icon: 'document' }, { id: 'frameworks-templates', label: 'Frameworks & Templates', icon: 'document' }, { id: 'implementation-roadmap', label: 'Implementation Roadmap', icon: 'bar-chart' }, { id: 'participant-feedback', label: 'Participant Feedback', icon: 'document' }, { id: 'project-outputs', label: 'Project Outputs', icon: 'document' }, { id: 'strategy-document', label: 'Strategy Document', icon: 'document' }, { id: 'session-recordings', label: 'Session Recordings', icon: 'video' }, { id: 'action-plan', label: 'Action Plan', icon: 'check-circle' }, { id: 'assessment-reports', label: 'Assessment Reports', icon: 'document' }, { id: 'skill-assessment-scores', label: 'Skill Assessment Scores', icon: 'bar-chart' }, { id: 'prototype-solution', label: 'Prototype or Solution', icon: 'wrench' }, { id: 'decision-framework', label: 'Decision Framework', icon: 'document' }, { id: 'toolkits', label: 'Toolkits', icon: 'wrench' }, { id: 'post-session-summary', label: 'Post-Session Summary', icon: 'document' }, { id: 'coaching-notes', label: 'Coaching Notes', icon: 'document' }, { id: 'certification', label: 'Certification', icon: 'check-circle' }, { id: 'custom-playbooks', label: 'Custom Playbooks', icon: 'document' }, { id: 'performance-tracking', label: 'Performance Tracking', icon: 'bar-chart' }]
export const DELIVERABLE_FORMAT_OPTIONS = ['PDF Document', 'Video Recording', 'Interactive Tool', 'Dashboard/Portal', 'Presentation Slides', 'Spreadsheet']
export const DELIVERY_TIMELINE_OPTIONS = ['During session', 'Immediately After', 'within 1 week', 'within 2 weeks', 'within 1 month']
export const DELIVERABLE_OWNERSHIP_OPTIONS = ['Experts Retain IP', 'Client Owns Fully', 'Shared Ownership']
export const ENGAGEMENT_TYPE_OPTIONS = [{ id: 'keynote', title: 'Keynote Session', tag1: 'low intensity', tag2: 'low outcome' }, { id: 'panel', title: 'Panel Discussion', tag1: 'low intensity', tag2: 'low outcome' }, { id: 'fireside', title: 'Fireside Chat', tag1: 'low intensity', tag2: 'medium outcome' }, { id: 'workshop-single', title: 'Workshop (Single Day)', tag1: 'high intensity', tag2: 'medium outcome' }, { id: 'workshop-multi', title: 'Workshop (Multi-Day)', tag1: 'high intensity', tag2: 'high outcome' }, { id: 'bootcamp', title: 'Bootcamp', tag1: 'high intensity', tag2: 'high outcome' }, { id: 'coaching-1on1', title: 'Coaching (1-on-1)', tag1: 'high intensity', tag2: 'high outcome' }, { id: 'coaching-group', title: 'Coaching (Group)', tag1: 'high intensity', tag2: 'high outcome' }, { id: 'mentorship', title: 'Mentorship Program', tag1: 'medium intensity', tag2: 'high outcome' }, { id: 'advisory', title: 'Advisory Session', tag1: 'medium intensity', tag2: 'high outcome' }, { id: 'strategy-offsite', title: 'Strategy Offsite', tag1: 'high intensity', tag2: 'high outcome' }, { id: 'roundtable', title: 'Roundtable', tag1: 'medium intensity', tag2: 'medium outcome' }, { id: 'hackathon', title: 'Hackathon', tag1: 'high intensity', tag2: 'high outcome' }, { id: 'masterclass', title: 'Masterclass', tag1: 'medium intensity', tag2: 'high outcome' }, { id: 'webinar', title: 'Webinar', tag1: 'low intensity', tag2: 'low outcome' }, { id: 'training', title: 'Training Program', tag1: 'high intensity', tag2: 'high outcome' }, { id: 'implementation', title: 'Implementation Sprint', tag1: 'high intensity', tag2: 'high outcome' }]
export const DELIVERY_MODE_OPTIONS = [{ id: 'in-person', title: 'In-Person', tag: 'low scalability' }, { id: 'virtual', title: 'Virtual (Live)', tag: 'high scalability' }, { id: 'hybrid', title: 'Hybrid', tag: 'medium scalability' }, { id: 'async', title: 'Async (Recorded)', tag: 'very_high scalability' }, { id: 'blended', title: 'Blended', tag: 'medium scalability' }]
export const DELIVERY_PLATFORM_OPTIONS = ['Zoom', 'Microsoft Teams', 'Google Meet', 'WebEx', 'Other']
export const OUTCOME_ORIENTATION_OPTIONS = ['Low', 'Medium', 'High']
export const SESSION_PATTERN_OPTIONS = ['single_session', 'multi_session_fixed', 'recurring']
export const FLEXIBILITY_LEVEL_OPTIONS = ['Fixed- Dates', 'Semi flexibile', 'Fully flexible']
export const URGENCY_LEVEL_OPTIONS = ['Immediate(<7 Days)', 'Short Terms (1-4 weeks)', 'Planned (13 Months)', 'Long Terms(3+ Months)']
export const VENUE_TYPE_OPTIONS = ['Office', 'External venue', 'Virtual', 'Client site', 'Other']
export const PREPARATION_TIME_OPTIONS = [{ id: 'no_prep', title: 'No Prep', description: 'Less than 2 days', risk: 'high risk', riskClass: 'bg-red-500 text-white' }, { id: 'low', title: 'Low', description: '3-7 days', risk: 'medium risk', riskClass: 'bg-amber-200 text-gray-800' }, { id: 'moderate', title: 'Moderate', description: '1-3 weeks', risk: 'low risk', riskClass: 'bg-green-200 text-green-900' }, { id: 'high', title: 'High', description: '3+ weeks', risk: 'very_low risk', riskClass: 'bg-green-600 text-white' }]
export const LEARNING_MODES = ['Awareness', 'Practical', 'Applied'] as const
export const SECONDARY_OBJECTIVES = ['increase engagement', 'improve retention', 'drive action post event', 'build thought leadership', 'enable cross team collaboration', 'improve decision making', 'increase tool adoption', 'generate followup opportunities', 'improve confidence', 'create accountability', 'accelerate execution', 'improve communication', 'increase participation', 'build internal alignment']
